### ISSUE TITLE
Binaries for newer versions of libgit2?

### ISSUE THREAD

**Issue by tompazourek** [libgit2/libgit2sharp.nativebinaries#110]
The latest version of libgit2sharp.nativebinaries NuGet package contains binaries for the version 0.28.0 of libgit2. However, there have been many releases since:

- 0.28.1
- 0.28.2
- 0.28.3
- 0.28.4
- 0.28.5
- 0.99.0
- 1.0.0
- 1.0.1
- 1.1.0

They contain some useful fixes that would be nice to have. Are there any plans to publish binaries for these newer versions?

Thanks

**Comment by DvdKhl** [comment]
I'm also wondering if there is a particular reason why it isn't updated to a newer version.

I've cloned both repositories libgit2sharp and this one, made a few changes to get it running with net5 and Visual Studio 2019.
Then I've updated/compiled/packaged this repo to use the source of libgit2 1.1.0 with the provided scripts.

Then I ran the tests in LibGit2Sharp.Tests (which uses the new binary package) and only 5 tests failed:
![image](https://user-images.githubusercontent.com/3011432/121777904-a93ede00-cb94-11eb-8e45-8bf476dadcab.png)

I think it would be nice to have an additional nuget alpha preview release of libgit2sharp with the 1.1.0 binaries, so more people are able to test it.

**Comment by rgl** [comment]
This now seems to be available at:

* https://github.com/libgit2/libgit2sharp.nativebinaries/pull/114
* https://github.com/libgit2/libgit2sharp.nativebinaries/pull/115

But it seems there is no one looking at this project anymore :-(

**Comment by jairbubbles** [comment]
@DvdKhl  With the package produced by #114 I was able to run all tests successfully with only a few minor changes. "origin/HEAD" is now added when cloning (see https://github.com/libgit2/libgit2/pull/5651) and some tests are failing because they are counting the branches after clone.

I didn't have any issue with `CanGetBlobAsTextWithVariousEncodings` or `NoPublicTypesUnderLibGit2SharpCoreNamespace`.

I will create a PR but I need to reference the new package which is not on nuget.org for the CI to pass.

**Comment by bording** [comment]
@jairbubbles #114 has been merged, and I've published 2.0.315-alpha.0.1 with the changes.

**Comment by jairbubbles** [comment]
Looks awesome to me!

**Comment by jairbubbles** [comment]
I create a draft PR here in libGit2Sharp => https://github.com/libgit2/libgit2sharp/pull/1905/

**Comment by bording** [comment]
Since we now have packages up on nuget.org with newer versions, I'm going to go ahead and close this.
